### ISSUE TITLE
Annotating complexes still isn’t working right

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua-visual-pathway-editor#2] opened 2022-02-28 15:28 UTC
See model http://bioghost2.usc.edu:4205/workbench/visual-pathway-editor/?model_id=gomodel%3A6215405200000034
The model has a complex of which CDK1 is a part
<img width="468" alt="image" src="https://user-images.githubusercontent.com/4782928/156010004-084496a6-65ec-4a7a-8afb-3e4efe7b52ba.png">

But the visual editor shows CDK1 as the enabler. Note that the curator also cannot attach evidence to the MF, possibly because there’s no actual edge between CDK1 and the MF.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/4782928/156010121-d6cfd4a7-9b28-445d-9885-ee0ca32ece3b.png">

**Comment by tmushayahama** [comment] 2022-03-10 22:41
The model is gone, but lemme try to make similar one.

**Comment by tmushayahama** [comment] 2022-03-10 23:02
@pgaudet @pgaudet The problem is a potential wrong model. If you see it has 2 types for MF (protein kinase activity and molecular_function), so it crashes. Will that be the case or it as a wrong model?  I just remade the model it seems to be working, if only one type was made.

![image](https://user-images.githubusercontent.com/2273929/157769032-32254edd-552c-42c8-9f93-bf8f7cb52135.png)

Visual Editor
![image](https://user-images.githubusercontent.com/2273929/157769556-9a51debe-00cf-4a3f-ac36-90bf88d34af3.png)

**Comment by thomaspd** [comment] 2022-03-11 14:22
I agree this seems to be working now. I'll close this issue.

**Closed by thomaspd** 2022-03-11 14:22 UTC
Labels: bug, show stopper bug
